version: "3"

env:
  VERSION: 0.4.1

dotenv: [".env"]

tasks:
  test:
    cmds:
      - task build
      - task docker-build

  build:
    cmds:
      - go build -ldflags "-X github.com/damongolding/eventsforce/cmd/version.version={{.VERSION}}" -o dist/eventsforce .

  commit-tag:
    - git add .
    - git commit -m "{{.MESSAGE}}"
    - git push
    - git tag -fa v$VERSION -m "{{.MESSAGE}}"
    - git push origin v$VERSION

  tag:
    cmds:
      - git tag -fa v$VERSION -m "{{.MESSAGE}}"
      - git push origin v$VERSION

  release-local:
    cmds:
      - VERSION={{.VERSION}} goreleaser release --snapshot --clean

  goreleaser:
    cmds:
      - GITHUB_TOKEN=$GUTHUB_TOKEN VERSION={{.VERSION}} goreleaser release --clean
      - rm -r dist

  release:
    deps: ["goreleaser", "docker-image-push"]

  docker-image:
    cmds:
      - docker build --build-arg VERSION={{.VERSION}} --build-arg TAILWIND_VERSION={{.TAILWIND_VERSION}} -t damongolding/eventsforce:{{.VERSION}}  -t damongolding/eventsforce:latest .
    vars:
      TAILWIND_VERSION:
        sh: 'curl -L -H "Accept: application/vnd.github+json" https://api.github.com/repos/tailwindlabs/tailwindcss/releases/latest | jq -r ".tag_name" | sed "s/^v//"'

  docker-image-push:
    cmds:
      - docker build --build-arg VERSION={{.VERSION}} --build-arg TAILWIND_VERSION={{.TAILWIND_VERSION}} --platform linux/amd64,linux/arm64 --push -t damongolding/eventsforce:{{.VERSION}}  -t damongolding/eventsforce:latest .
    vars:
      TAILWIND_VERSION:
        sh: 'curl -L -H "Accept: application/vnd.github+json" https://api.github.com/repos/tailwindlabs/tailwindcss/releases/latest | jq -r ".tag_name" | sed "s/^v//"'

  docker-build:
    cmds:
      - docker run -it --rm -e TERM=xterm-256color -e DEBUG_COLORS=true -e COLORTERM=truecolor -v "${PWD}/:/templates" --user 1000:1000 damongolding/eventsforce build

  docker-dev:
    cmds:
      - docker run -it --rm -e TERM=xterm-256color -e DEBUG_COLORS=true -e COLORTERM=truecolor -v "${PWD}/:/templates" -p 3000:3000 -p 35729:35729 --user 1000:1000 damongolding/eventsforce serve

  docker-version:
    cmds:
      - docker run -it --rm -e TERM=xterm-256color -e DEBUG_COLORS=true -e COLORTERM=truecolor -v "${PWD}/:/templates" damongolding/eventsforce version

  docker-new:
    cmds:
      - docker run -it --rm -e TERM=xterm-256color -e DEBUG_COLORS=true -e COLORTERM=truecolor -v "${PWD}/:/templates" damongolding/eventsforce new
