version: "3"

env:
  VERSION: v0.1.9

dotenv: [".env"]

tasks:
  build:
    cmds:
      - go build -ldflags "-X github.com/damongolding/eventsforce/cmd/version.version={{.VERSION}}" -o dist/eventsforce .

  tag:
    cmds:
      - git add .
      - git commit -m "{{.MESSAGE}}"
      - git push
      - git tag -a $VERSION -m "{{.MESSAGE}}"
      - git push origin $VERSION

  release:
    cmds:
      - GITHUB_TOKEN=$GUTHUB_TOKEN VERSION={{.VERSION}} goreleaser release --clean
