version: "3"

env:
  VERSION: v0.2.0

dotenv: [".env"]

tasks:
  build:
    cmds:
      - go build -ldflags "-X github.com/damongolding/eventsforce/cmd/version.version={{.VERSION}}" -o dist/eventsforce .

  tag:
    cmds:
      - git add .
      - git commit -m "{{.MESSAGE}}"
      - git push
      - git tag -a $VERSION -m "{{.MESSAGE}}"
      - git push origin $VERSION

  release-local:
    cmds:
      - VERSION={{.VERSION}} goreleaser release --snapshot --clean

  release:
    cmds:
      - GITHUB_TOKEN=$GUTHUB_TOKEN VERSION={{.VERSION}} goreleaser release --clean


  docker-build:
    cmds:
      - docker run -it -e "TERM=xterm-256color" -v "${PWD}/:/eventsforce" -p 3000:3000 eventsforce build
