version: "3"

env:
  VERSION: 0.2.6

dotenv: [".env"]

tasks:
  build:
    cmds:
      - go build -ldflags "-X github.com/damongolding/eventsforce/cmd/version.version=v{{.VERSION}}" -o dist/eventsforce .

  tag:
    cmds:
      - git add .
      - git commit -m "{{.MESSAGE}}"
      - git push
      - git tag -fa v$VERSION -m "{{.MESSAGE}}"
      - git push origin v$VERSION

  release-local:
    cmds:
      - VERSION={{.VERSION}} goreleaser release --snapshot --clean

  release:
    deps: [docker-image-push]
    cmds:
      - GITHUB_TOKEN=$GUTHUB_TOKEN VERSION={{.VERSION}} goreleaser release --clean
      - rm -r dist

  docker-image:
    cmds:
      - docker build --build-arg VERSION=v{{.VERSION}} --platform linux/amd64,linux/arm64 -t damongolding/eventsforce:{{.VERSION}}  -t damongolding/eventsforce:latest .

  docker-image-push:
    cmds:
      - docker build --build-arg VERSION=v{{.VERSION}} --platform linux/amd64,linux/arm64 --push -t damongolding/eventsforce:{{.VERSION}}  -t damongolding/eventsforce:latest .

  docker-build:
    cmds:
      - docker run -it --rm -e "TERM=xterm-256color --color=always"  -v "${PWD}/:/eventsforce" --user 1000:1000 damongolding/eventsforce build

  docker-dev:
    cmds:
      - docker run --rm -it -e "TERM=xterm-256color" -v "${PWD}/:/eventsforce" -p 3000:3000 -p 35729:35729 --user 1000:1000 damongolding/eventsforce serve

  docker-version:
    cmds:
      - docker run -it --rm -e "TERM=xterm-256color" -v "${PWD}/:/eventsforce" damongolding/eventsforce version

  docker-new:
    cmds:
      - docker run -it --rm -e "TERM=xterm-256color" -v "${PWD}/:/eventsforce" damongolding/eventsforce new
